<?php
/**
 * Evolucard
 *
 * @category   Payments
 * @package    Xpd_Evolucardgateway
 * @license    OSL v3.0
 * @author     Denis Spalenza - http://www.xpd.com.br/
 *   
 */
 ?>
<?php
    $_code=$this->getMethodCode();
    //feito para ter compatibilidade com o OneStepCheckout
    $route = $this->getRequest()->getRequestedRouteName();
    if($route == 'onestepcheckout') {
        $fieldCode = '['.$_code.']';
    }
    else {
        $fieldCode = '';
    }
    $cls  = new Mage_Core_Model_Design_Package();
    $path = $cls->getSkinBaseUrl();
    $contaParcela = 1;
?>

<script type="text/javascript">
function onCardChange(optElement) {
    var meuID = optElement.id;
    var selCard = optElement.value; 
    
    if (selCard == 'diners') {
        $('<?php echo $_code ?>_cc_number').setAttribute('maxlength', 14);
    }
    else {
        if (selCard == 'amex') {
            $('<?php echo $_code ?>_cc_number').setAttribute('maxlength', 15);
        }
        else {
            $('<?php echo $_code ?>_cc_number').setAttribute('maxlength', 16);
        }
    }

    //quando um tipo de cartao e escolhida, limpa a escolha dos outros campos de tipo de cartao
    $('evolucardgateway_cc_number').value = "";
    $('evolucardgateway_cc_cid').value = "";
}
function mascara(o,f){
    v_obj=o
    v_fun=f
    setTimeout("execmascara()",1)
}
function execmascara(){
    v_obj.value=v_fun(v_obj.value)
}
function numeros(v){
    v=v.replace(/\D/g,"")
    return v
}
</script>
<fieldset class="form-list">
<?php $_ccType = $this->getInfoData('cc_type') ?>
<?php $parcela2 = end($this->getParcelas()); ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li  style="display: block">
        <div class="input-box">
            <?php if(Mage::getStoreConfig('payment/evolucardgateway/ativarlabel')): ?>
            <div style="width: 99.5%; height: 25px;">
            <label for="card-logo" class="required"><em>*</em><?php echo $this->__('Selecione sua Bandeira') ?></label>
            </div>
            <?php endif; ?>
            <ul class="card-logo">
    		<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
    			<li id="li-card-<?php echo $_typeCode ?>" class="seleciona-bandeiras-cards">
    				<label for="opt-<?php echo $_typeCode ?>"><img src="<?php echo $this->getSkinUrl('images/evolucardgateway/'.$_typeCode.'/'. $parcela2['parcela'] .'x.gif') ?>" /></label>
                    
                    <input type="radio" class="radio" name="payment[cc_type]" id="opt-<?php echo $_typeCode ?>" value="<?php echo $_typeCode ?>" onclick="onCardChange(this);"/>
    			</li>
    		<?php endforeach; ?>
    		</ul>
        </div>
    </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label><br />
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label><br />
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" class="input-text required-entry" value="" maxlength="16" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label><br />
        <div class="input-box">
            <div class="v-fix">
                <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month required-entry">
                <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v[0] == 'M' ? $v : substr($v,0,3); ?></option>
                <?php endforeach ?>
                </select>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                <?php foreach ($this->getCcYears() as $k=>$v): ?>
                    <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label><br />
        <div class="input-box">
            <div class="v-fix">
                <input type="text" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" size="5" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" maxlength="4" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
    <li style="margin-bottom: 20px;">
        <label for="<?php echo $_code ?>_parcelas"><?php echo $this->__('Parcelas') ?> </label><br />
        <div class="input-box">
            <select id="<?php echo $_code ?>_cc_parcelas" name="payment[cc_parcelas]">
		<?php foreach($this->getParcelas() as $parcela): ?>
				<option value="<?php echo $parcela['parcela'] ?>"><?php echo $parcela['label'] ?></option>
		<?php endforeach ?>
	    </select>
        </div>
    </li>
    <?php if(Mage::getStoreConfig('payment/evolucardgateway/cadastroone')): ?>
        <?php $checkout = Mage::getSingleton('checkout/session')->getQuote(); ?>
        <?php $billing = $checkout->getBillingAddress();
        $tel_b = $billing->getData("telephone");
        $cel_b = $billing->getData("fax");
        
        $tel_ddd = substr($tel_b,1,2);
        $cel_ddd = substr($cel_b,1,2);
        
        $cel_num = substr($cel_b,4);
        $tel_num = substr($tel_b,4);    
        ?>
        <li class="form-evolucard-create-account">
            <div class="input-box">
                <input type="checkbox" id="<?php echo $_code ?>_create_account" name="payment[create_account]" onclick="ChkBoxMethod();" checked="yes" />
                <label style="float: right; width: 275px;" for="<?php echo $_code ?>_create_account"><?php echo $this->__('Aceito pagar com 1-Click') . ' ' . (Mage::getStoreConfig('payment/evolucardgateway/storename') ? Mage::getStoreConfig('payment/evolucardgateway/storename') : Mage::app()->getStore()->getName()) . ' ' . $this->__('na próxima compra'); ?></label>
            </div>
        </li>
        <?php //if((strlen($cel_num) == 8 || strlen($cel_num) == 9) && strlen($cel_ddd) == 2): ?>
        <li class="form-evolucard-celular" id="form-evolucard-celular">
            <label class="required"><em>*</em>Celular</label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('DDI') ?>" placeholder="DDI" class="input-text ddi required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddi_cel" name="payment[ddi_cel]" value="55" maxlength="3" style="display: none;"/>
                <input type="text" title="<?php echo $this->__('DDD') ?>" placeholder="DDD" class="input-text ddd required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddd_cel" name="payment[ddd_cel]" value="<?php echo strlen($cel_num) == 8 || strlen($cel_num) == 9 ? $cel_ddd : ''; ?>" maxlength="3" />
                <input type="text" title="<?php echo $this->__('Celular') ?>" placeholder="Celular" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" class="input-text number required-entry" size="9" id="<?php echo $_code ?>_number_cel" name="payment[number_cel]" value="<?php echo strlen($cel_num) == 8 || strlen($cel_num) == 9 ? $cel_num : ''; ?>" maxlength="9" />
            </div>
        </li>
        <?php if((strlen($tel_num) == 8 || strlen($tel_num) == 9) && strlen($tel_ddd) == 2): ?>
        <li class="form-evolucard-telefone" id="form-evolucard-telefone-inputado" style="display: none;">
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('DDI') ?>" placeholder="DDI" class="input-text ddi required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddi_tel" name="payment[ddi_tel]" value="55" maxlength="3" style="display: none;"/>
                <input type="text" title="<?php echo $this->__('DDD') ?>" placeholder="DDD" class="input-text ddd required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddd_tel" name="payment[ddd_tel]" value="<?php echo strlen($tel_num) == 8 || strlen($tel_num) == 9 ? $tel_ddd : ''; ?>" maxlength="3" />
                <input type="text" title="<?php echo $this->__('Telefone') ?>" placeholder="Telefone" class="input-text number required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="9" id="<?php echo $_code ?>_number_tel" name="payment[number_tel]" value="<?php echo strlen($tel_num) == 8 || strlen($tel_num) == 9 ? $tel_num : ''; ?>" maxlength="9" />
            </div>
        </li>
        <?php else: ?>
        <li class="form-evolucard-telefone" id="form-evolucard-telefone">
            <label class="required"><em>*</em>Telefone</label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('DDI') ?>" placeholder="DDI" class="input-text ddi required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddi_tel" name="payment[ddi_tel]" value="55" maxlength="3" style="display: none;"/>
                <input type="text" title="<?php echo $this->__('DDD') ?>" placeholder="DDD" class="input-text ddd required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddd_tel" name="payment[ddd_tel]" value="<?php echo strlen($tel_num) == 8 || strlen($tel_num) == 9 ? $tel_ddd : ''; ?>" maxlength="3" />
                <input type="text" title="<?php echo $this->__('Telefone') ?>" placeholder="Telefone" class="input-text number required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="9" id="<?php echo $_code ?>_number_tel" name="payment[number_tel]" value="<?php echo strlen($tel_num) == 8 || strlen($tel_num) == 9 ? $tel_num : ''; ?>" maxlength="9" />
            </div>
        </li>
        <?php endif; ?>
    <?php else: ?>
        <?php $checkout = Mage::getSingleton('checkout/session')->getQuote(); ?>
        <?php $billing = $checkout->getBillingAddress();
        $tel_b = $billing->getData("telephone");
        $cel_b = $billing->getData("fax");
        
        $tel_ddd = substr($tel_b,1,2);
        $cel_ddd = substr($cel_b,1,2);
        
        $cel_num = substr($cel_b,4);
        $tel_num = substr($tel_b,4);    
        ?>
        
        <?php //if((strlen($cel_num) == 8 || strlen($cel_num) == 9) && strlen($cel_ddd) == 2): ?>
        <li class="form-evolucard-celular" id="form-evolucard-celular" style="display: none;">
            <label class="required"><em>*</em>Celular</label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('DDI') ?>" placeholder="DDI" class="input-text ddi required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddi_cel" name="payment[ddi_cel]" value="55" maxlength="3" style="display: none;"/>
                <input type="text" title="<?php echo $this->__('DDD') ?>" placeholder="DDD" class="input-text ddd required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddd_cel" name="payment[ddd_cel]" value="<?php echo strlen($cel_num) == 8 || strlen($cel_num) == 9 ? $cel_ddd : ''; ?>" maxlength="3" />
                <input type="text" title="<?php echo $this->__('Celular') ?>" placeholder="Celular" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" class="input-text number required-entry" size="9" id="<?php echo $_code ?>_number_cel" name="payment[number_cel]" value="<?php echo strlen($cel_num) == 8 || strlen($cel_num) == 9 ? $cel_num : ''; ?>" maxlength="9" />
            </div>
        </li>
        <?php if((strlen($tel_num) == 8 || strlen($tel_num) == 9) && strlen($tel_ddd) == 2): ?>
        <li class="form-evolucard-telefone" id="form-evolucard-telefone-inputado" style="display: none;">
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('DDI') ?>" placeholder="DDI" class="input-text ddi required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddi_tel" name="payment[ddi_tel]" value="55" maxlength="3" style="display: none;"/>
                <input type="text" title="<?php echo $this->__('DDD') ?>" placeholder="DDD" class="input-text ddd required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddd_tel" name="payment[ddd_tel]" value="<?php echo strlen($tel_num) == 8 || strlen($tel_num) == 9 ? $tel_ddd : ''; ?>" maxlength="3" />
                <input type="text" title="<?php echo $this->__('Telefone') ?>" placeholder="Telefone" class="input-text number required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="9" id="<?php echo $_code ?>_number_tel" name="payment[number_tel]" value="<?php echo strlen($tel_num) == 8 || strlen($tel_num) == 9 ? $tel_num : ''; ?>" maxlength="9" />
            </div>
        </li>
        <?php else: ?>
        <li class="form-evolucard-telefone" id="form-evolucard-telefone" style="display: none;">
            <label class="required"><em>*</em>Telefone</label>
            <div class="input-box">
                <input type="text" title="<?php echo $this->__('DDI') ?>" placeholder="DDI" class="input-text ddi required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddi_tel" name="payment[ddi_tel]" value="55" maxlength="3" style="display: none;"/>
                <input type="text" title="<?php echo $this->__('DDD') ?>" placeholder="DDD" class="input-text ddd required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="3" id="<?php echo $_code ?>_ddd_tel" name="payment[ddd_tel]" value="<?php echo strlen($tel_num) == 8 || strlen($tel_num) == 9 ? $tel_ddd : ''; ?>" maxlength="3" />
                <input type="text" title="<?php echo $this->__('Telefone') ?>" placeholder="Telefone" class="input-text number required-entry" onkeyup="mascara(this,numeros)" onfocus="mascara(this,numeros)" onblur="mascara(this,numeros)" size="9" id="<?php echo $_code ?>_number_tel" name="payment[number_tel]" value="<?php echo strlen($tel_num) == 8 || strlen($tel_num) == 9 ? $tel_num : ''; ?>" maxlength="9" />
            </div>
        </li>
        <?php endif; ?>
    <?php endif; ?>
</ul>
</fieldset>
<script type="text/javascript">

function ChkBoxMethod(){
    if(!$('evolucardgateway_create_account').checked) { // Desmarcar
         $('form-evolucard-celular').hide();
         $('form-evolucard-telefone').hide();
    }
    else { // Marcar
        $('form-evolucard-celular').show();
        $('form-evolucard-telefone').show();
    }
}

</script>

