<?php
/**
 * Octagono Ecommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 *
 *
 * @category   Cielo
 * @package    Octagono_Cielo
 * @copyright  Copyright (c) 2009-2011 - Octagono Ecommerce - www.octagonoecommerce.com.br
 * @license    http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 */

$orderId = 0;
$realOrderId = 0;

$order = $this->getOrder();

if ($order) {
	$orderId = $order->getId();
	$realOrderId = $order->getRealOrderId();
}
else {
	$orderId = Mage::getSingleton('checkout/session')->getLastOrderId();
	$realOrderId = Mage::getSingleton('checkout/session')->getLastRealOrderId();
}
 ?>
<?php $additionaldata = unserialize($this->getInfo()->getData('additional_data')); ?>
<?php $parcelas = isset($additionaldata["cc_parcelas"]) ? $additionaldata["cc_parcelas"] : '' ?>
<?php $status = isset($additionaldata["status"]) ? $additionaldata["status"] : '' ?>
<?php if(isset($additionaldata["autorizacao"])){
	$autorizacao = $this->__('Mensagem da transação: (%s) %s', $additionaldata["autorizacao"]['codigo'], $additionaldata["autorizacao"]['mensagem']);
}else{
	$autorizacao = "";
} ?>
<?php if(isset($additionaldata["captura"])){
	$captura = $additionaldata["captura"]['mensagem'];
}else{
	$captura = "";
} ?>
<?php if(isset($additionaldata["cancelamento"])){
	$cancelamentoMensagem = $additionaldata["cancelamento"]['mensagem'];
	$cancelamentoCodigo = $additionaldata["cancelamento"]['codigo'];
}else{
	$cancelamentoMensagem = "";
} ?>


<p><?php echo $this->__('Name on the Card: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?></p>
<p><?php echo $this->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?></p>
<p><?php echo $this->__('Credit Card Number: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?></p>
<p><?php echo $this->__('Expiration Date: %s/%s', $this->htmlEscape($this->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?></p>
<p><?php echo $this->__('Número de Parcelas: %s', $parcelas) ?></p>
<?php if(isset($additionaldata["tid"])): ?>

	<?php if($additionaldata["tid"]): ?>
		<p><?php echo $this->__('Código da transação: %s', $additionaldata["tid"]) ?></p>
	<?php endif ?>
	
	<?php if(isset($additionaldata["erro"])): ?>
		<p><?php echo $this->__('Mensagem da transação: (%s) %s', $additionaldata["erro"]['codigo'], $additionaldata["erro"]['mensagem']) ?></p>
	<?php elseif(isset($additionaldata["autorizacao"])): ?>
		<p style="font-weight: bold; color: <?php echo ($status == 4 || $status == 6) ? '#056840' : '#FF0400' ?>"><?php echo $autorizacao ?></p>
		
		<?php if(!$cancelamentoMensagem): ?>	
			<?php if(!$captura  && $status == 4 || $status == 6): ?>	
				<div class="buttons-set">
					<button type="button" class="scalable save" onclick="window.open('<?php echo Mage::getUrl('cielo/standard/captura', array('order_id' => $this->getOrder()->getId())) ?>', 'captura', 'width=400,height=400');" style=""><span>Clique aqui para Capturar</span></button>
	
					<button type="button" class="scalable save" onclick="window.open('<?php echo Mage::getUrl('cielo/standard/cancelamento', array('order_id' => $this->getOrder()->getId())) ?>', 'cancelamento', 'width=400,height=400');" style=""><span>Clique aqui para Cancelar</span></button>	
				</div>	
			<?php endif ?>
		<?php endif ?>
		
	<?php endif ?>
	
    <?php if($captura): ?>
        <p><b><?php echo $captura ?></b></p>
    <?php elseif($cancelamentoMensagem): ?>
        <p><b>Status atual da transação: <?php echo "(".$cancelamentoCodigo.") ".$cancelamentoMensagem ?></b></p>
    <?php endif ?>
    
	<div class="buttons-set">
		<button type="button" class="scalable save" onclick="window.open('<?php echo Mage::getUrl('cielo/standard/consulta', array('order_id' => $this->getOrder()->getId())) ?>', 'consulta', 'width=400,height=400');" style=""><span>Consultar histórico da transação</span></button>		
	</div>
<?php endif ?>

