<?php
/**
 * Octagono Ecommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 *
 *
 * @category   Cielo
 * @package    Octagono_Cielo
 * @copyright  Copyright (c) 2009-2011 - Octagono Ecommerce - www.octagonoecommerce.com.br
 * @license    http://www.octagonoecommerce.com.br/eula-licenca-usuario-final.html
 */
 ?>
<?php  
	$_code=$this->getMethodCode();
	$cls  = new Mage_Core_Model_Design_Package();
	$path = $cls->getSkinBaseUrl();
?>

<script type="text/javascript">
    function onCardChange(selectElement) {
        var selCard = selectElement.options[selectElement.selectedIndex].value;
        alert(selCard);
        
        if (selCard == 'amex') {
            $('<?php echo $_code ?>_cc_cid').setAttribute('maxlength', 4);
        }
        else {
            $('<?php echo $_code ?>_cc_cid').setAttribute('maxlength', 3);
        }
    }
</script>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">


        <li>
            <div class="input-box">
                <label for="<?php echo $_code ?>_cc_type"><?php echo $this->__('Credit Card Type') ?> <span class="required">*</span></label><br />
                <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cartao-type-select">
                    <option value=""><?php echo $this->__('--Please Select--') ?></option>
                <?php $_ccType = $this->getInfoData('cc_type') ?>
                <?php $ccTypes = $this->getCcAvailableTypes(); ?>
                <?php foreach ($ccTypes as $_typeCode => $_typeName): ?>
                    <?php
                        if (count($ccTypes) == 1 || $_typeCode == $_ccType) {
                            $selected = 'selected="selected"';
                        }
                        else {
                            $selected = '';
                        }
                    ?>
                    <option value="<?php echo $_typeCode ?>" <?php echo $selected; ?>><?php echo $_typeName ?></option>
                <?php endforeach ?>
                </select>
            </div>
        </li>
    <li>
        <div class="input-box">
            <label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label><br />
            <input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text required-entry" id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="Nome no Cartão" />
        </div>
    </li>
    <li>
        <label for="<?php echo $_code ?>_cc_number" class="required"><?php echo $this->__('Credit Card Number') ?></label><br />
        <div class="input-box">
            <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text" value="4551870000000183" maxlength="16" />
        </div>
    </li>
    <li id="<?php echo $_code ?>_cc_type_exp_div">
        <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label><br />
        <div class="input-box">
            <div class="v-fix">
                <input type="text" id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="input-text required-entry" value="08"/>
            </div>
            <div class="v-fix">
                <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                <input type="text" id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="input-text required-entry" value="2015"/>
                </select>
            </div>
        </div>
    </li>
    <?php echo $this->getChildHtml() ?>
    <?php if($this->hasVerification()): ?>
    <li>
        <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label><br />
        <div class="input-box">
            <div class="v-fix">
                <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry" size="5" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="973" maxlength="4" />
            </div>
            <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
        </div>
    </li>
    <?php endif; ?>
    <li>
        <label for="<?php echo $_code ?>_parcelas"><?php echo $this->__('Parcelas') ?> </label><br />
        <div class="input-box">
        <select id="<?php echo $_code ?>_cc_parcelas" name="payment[cc_parcelas]">
			<?php foreach($this->getParcelas() as $parcela): ?>
					<option value="<?php echo $parcela['parcela'] ?>"><?php echo $parcela['label'] ?></option>
			<?php endforeach ?>
	    </select>
        </div>
    </li>
</ul>

<style type="text/css">
.card-logo { }
.card-logo li { float: left; text-align: center; margin-right: 15px !important;height:57px;vertical-align:bottom;display:block; position:relative; }
.card-logo li .validation-advice {position:absolute;top:55px;width:150px}
.payment-methods .form-list li .input-box .input-text.cvv { width:50px; margin-right:5px}
.payment-methods .form-list li .input-box select { width:auto !important;margin-right:5px}
</style>

